#!/usr/bin/env python3
"""Generates chrome.css (ONLY the shared header, footer, dropdown and brand-wordmark rules + the :root variables) from style.css.
Pages that carry their own full design (lifeos-*.html, resume.html, openwallet-safety.html) load chrome.css instead of the whole style.css,
so the shared header/footer look identical everywhere without style.css's page rules (.hero etc.) clashing with the page's own CSS.
Run after ANY change to the header/footer/brand rules in style.css:  python3 build-chrome-css.py
"""
import re
css = open('style.css').read()
KEEP = r'^(:root|nav|footer)\b|^(\.nav-|\.dropdown|\.mobile-menu-btn|\.footer-|\.nutrisize-grad|\.ei-|\.t3|\.arc-)|nav-pill|nav-dropdown|footer|\.nav-|\.ei-|\.t3|dropdown'
def walk(text, in_media=False):
    out = []; i = 0
    while i < len(text):
        j = text.find('{', i)
        if j < 0: break
        sel = re.sub(r'/\*.*?\*/', '', text[i:j].split('}')[-1], flags=re.S).strip()
        d = 1; k = j + 1
        while k < len(text) and d:
            d += (text[k] == '{') - (text[k] == '}'); k += 1
        body = text[j + 1:k - 1]
        if sel.startswith('@media'):
            inner = walk(body, True)
            if inner.strip(): out.append(sel + ' {\n' + inner + '}\n')
        elif sel.startswith('@'):
            out.append(sel + ' {' + body + '}\n')
        elif sel == ':root' or all(re.search(KEEP, s.strip()) for s in sel.split(',')):
            out.append(sel + ' {' + body + '}\n')
        i = k
    return ''.join(out)
head = '/* GENERATED by build-chrome-css.py from style.css - do not edit by hand. Shared header/footer/brand only. */\n*,*::before,*::after{box-sizing:border-box}\n'
open('chrome.css', 'w').write(head + walk(css))
print('chrome.css written', len(open('chrome.css').read()), 'bytes')
